// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ShantiSangha.AgentFeedback.Data;

#nullable disable

namespace ShantiSangha.AgentFeedback.Migrations
{
    [DbContext(typeof(AgentFeedbackDbContext))]
    [Migration("20260516000000_InitAgentFeedback")]
    partial class InitAgentFeedback
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);
#pragma warning restore 612, 618
        }
    }
}
