// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ShantiSangha.Trading.Data;

#nullable disable

namespace ShantiSangha.Trading.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    [Migration("20260507120000_AddTradingSignalHorizons")]
    partial class AddTradingSignalHorizons
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);
#pragma warning restore 612, 618
        }
    }
}
