namespace ShantiSangha.Infrastructure.AI;

public static class SupportResources
{
    /// <summary>
    /// Returned verbatim when a crisis signal is detected. This message must never
    /// be generated by the AI — it is hardcoded and reviewed by humans.
    /// </summary>
    public const string CrisisResponse = """
        It sounds like you may be going through something really serious right now, and I want to make sure you get the right support.

        Please reach out to one of these resources — they are free, confidential, and available right now:

        **If you are in the US:**
        - 988 Suicide & Crisis Lifeline — call or text **988**
        - Crisis Text Line — text HOME to **741741**

        **If you are in the UK:**
        - Samaritans — call **116 123** (free, 24/7)
        - SHOUT Crisis Text Line — text SHOUT to **85258**

        **If you are in Australia:**
        - Lifeline — call **13 11 14**
        - Beyond Blue — call **1300 22 4636**

        **International:**
        - findahelpline.com lists crisis lines for most countries

        **If you are in immediate danger, please call your local emergency number (911, 999, 000) right now.**

        I care about your wellbeing and I am not equipped to provide the level of support you may need in this moment. Please talk to someone who can truly help.
        """;

    /// <summary>
    /// Returned when moderation flags content as harmful but not a crisis.
    /// </summary>
    public const string FlaggedResponse = """
        I am not able to continue this conversation in its current direction. If you are struggling, I am still here to listen — but I need us to approach this in a way that feels safe and supportive for you.

        If you are in crisis or need immediate help, please reach out to a crisis line. You can text HOME to 741741 (US) or call 988 at any time.
        """;

    /// <summary>
    /// Returned when the AI itself generates something that fails the output safety check.
    /// </summary>
    public const string ResponseFallback = """
        I want to make sure I respond to you in the most supportive way I can. Let me take a moment and try again — sometimes I need to find the right words.

        Could you tell me a bit more about what is on your mind right now?
        """;
}
