// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShantiSangha.Identity.Data;

#nullable disable

namespace ShantiSangha.Identity.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260425100000_AddProfileLocationDetails")]
    partial class AddProfileLocationDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShantiSangha.Identity.Models.DeviceToken", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Platform").IsRequired().HasColumnType("text");
                    b.Property<string>("Token").IsRequired().HasColumnType("text");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("Token").IsUnique();
                    b.HasIndex("UserId");
                    b.ToTable("DeviceTokens");
                });

            modelBuilder.Entity("ShantiSangha.Identity.Models.Profile", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateOnly?>("BirthDate").HasColumnType("date");
                    b.Property<string>("BirthPlace").HasColumnType("text");
                    b.Property<string>("BirthTime").HasColumnType("text");
                    b.Property<string>("City").HasColumnType("text");
                    b.Property<string>("Country").HasColumnType("text");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("DisplayName").HasColumnType("text");
                    b.Property<bool>("OnboardingCompleted").HasColumnType("boolean");
                    b.Property<int?>("ReminderHour").HasColumnType("integer");
                    b.Property<string>("State").HasColumnType("text");
                    b.Property<string>("Timezone").HasColumnType("text");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("UserId").IsUnique();
                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("ShantiSangha.Identity.Models.SafetyEvent", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<Guid?>("ConversationId").HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Details").HasColumnType("text");
                    b.Property<string>("EventType").IsRequired().HasColumnType("text");
                    b.Property<string>("TriggerContent").HasColumnType("text");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("UserId", "CreatedAt");
                    b.ToTable("SafetyEvents");
                });

            modelBuilder.Entity("ShantiSangha.Identity.Models.User", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("ClerkId").IsRequired().HasColumnType("text");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Email").IsRequired().HasColumnType("text");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("ClerkId").IsUnique();
                    b.HasIndex("Email").IsUnique();
                    b.ToTable("Users");
                });

            modelBuilder.Entity("ShantiSangha.Identity.Models.DeviceToken", b =>
                {
                    b.HasOne("ShantiSangha.Identity.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShantiSangha.Identity.Models.Profile", b =>
                {
                    b.HasOne("ShantiSangha.Identity.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("ShantiSangha.Identity.Models.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("ShantiSangha.Identity.Models.User", b =>
                {
                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
