// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShantiSangha.Chess.Data;

#nullable disable

namespace ShantiSangha.Chess.Migrations
{
    [DbContext(typeof(ChessDbContext))]
    [Migration("20260606215418_InitChess")]
    partial class InitChess
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShantiSangha.Chess.Models.ChessGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlackUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FriendshipId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastMoveUci")
                        .HasColumnType("text");

                    b.Property<int>("MoveCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WhiteUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WinnerUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BlackUserId");

                    b.HasIndex("FriendshipId");

                    b.HasIndex("WhiteUserId");

                    b.ToTable("ChessGames", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
