// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShantiSangha.Wellness.Data;

#nullable disable

namespace ShantiSangha.Wellness.Migrations
{
    [DbContext(typeof(WellnessDbContext))]
    [Migration("20260417200000_AddDailyReadings")]
    partial class AddDailyReadings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShantiSangha.Wellness.Models.DailyJournalPrompt", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("Content").IsRequired().HasColumnType("text");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<DateOnly>("Date").HasColumnType("date");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("UserId", "Date").IsUnique();
                    b.ToTable("DailyJournalPrompts");
                });

            modelBuilder.Entity("ShantiSangha.Wellness.Models.DailyReading", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("Content").IsRequired().HasColumnType("text");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<DateOnly>("Date").HasColumnType("date");
                    b.Property<string>("Framing").IsRequired().HasDefaultValue("regular").HasColumnType("text");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("UserId", "Date").IsUnique();
                    b.ToTable("DailyReadings");
                });

            modelBuilder.Entity("ShantiSangha.Wellness.Models.DailyReflection", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("Content").IsRequired().HasColumnType("text");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<DateOnly>("Date").HasColumnType("date");
                    b.Property<string>("Type").IsRequired().HasDefaultValue("Regular").HasColumnType("text");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("UserId", "Date").IsUnique();
                    b.ToTable("DailyReflections");
                });

            modelBuilder.Entity("ShantiSangha.Wellness.Models.Portrait", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("Content").IsRequired().HasColumnType("text");
                    b.Property<string>("ContextHash").IsRequired().HasColumnType("text");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("UserId").IsUnique();
                    b.ToTable("Portraits");
                });

            modelBuilder.Entity("ShantiSangha.Wellness.Models.VoiceEntry", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<Guid?>("DraftJournalId").HasColumnType("uuid");
                    b.Property<string>("Status").IsRequired().HasColumnType("text");
                    b.Property<string>("StorageKey").IsRequired().HasColumnType("text");
                    b.Property<string>("Transcript").HasColumnType("text");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.ToTable("VoiceEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
